### PR TITLE
Binomial

### PR DESCRIPTION
**Pull request by runarberg**
The of implementations  `pdf`, `cdf` and `inv_cdf` follows mostly similar methods that the *R* methods `dbinom`, `pbinom` and `qbinom`. I couldn't access good literature on generating a random sample in a similar manner as *R*’s `rbinom` so I just used a simple inversion.

### CODE REVIEW

**Comment by IvanUkhov** [comment]
@runarberg, thank you for the pull request. Could you please rebase it onto the master branch?

**Comment by IvanUkhov** [comment]
Turns out Binomials are much more complicated that I thought they were) That’s a lot of great work you’ve done!

**Comment by runarberg** [comment]
@IvanUkhov Thanks. I didn't know it either before diving in to it. The problems arise with large `n`s and get worse with low variances.

**Comment by IvanUkhov** [comment]
Thank you!

**Comment by IvanUkhov** [comment]
Hello, there have been found a case that does not converge:

https://github.com/stainless-steel/probability/blob/main/src/distribution/binomial.rs#L479-L484

Do you perhaps know if the original source has some kind of checks in place to adequately terminate the Newton method if too many iteration?

**Pull request merged**
