### PR TITLE
Added the bernoulli distribution

### PR DESCRIPTION
**Pull request by runarberg**

### CODE REVIEW

**Comment by runarberg** [comment]
I wonder if it's worth it to add the continuous/discrete distribution hierarchy?

**Comment by IvanUkhov** [comment]
@runarberg, regarding continuous/discrete hierarchy, I personally think that it is not worth it right now. Having traits for the two major classes would be good, but without strong motivation I would not complicate things. Without having a use case at hand, one might wind up developing something that is not that convenient to use in practice.

**Comment by runarberg** [comment]
@IvanUkhov Ok. let's leave things simple now then.

**Comment by IvanUkhov** [comment]
@runarberg, yes, let’s leave it for now. I’ve opened an [issue](https://github.com/stainless-steel/probability/issues/7) to keep track of this aspect.

**Comment by IvanUkhov** [comment]
Thank you!

**Pull request merged**
