### PR TITLE
Fix a PDF/CDF muff for Triangular and Logistic distributions

### PR DESCRIPTION
**Pull request by DenisKolodin**
Wow! I've found a strong mistake with density and distribution implementation I've pushed. This PR fixes it.

I've missed because I copied bodies from `Uniform` test which has different order instead of others, but check implementation coverage with `Exponential`.

### CODE REVIEW

**Comment by IvanUkhov** [comment]
It’s good that you’ve found this! Can you please explain how you generated the input/output data for the tests so that the tests were passing despite the fact that the functions that they were calling were incorrect?

**Comment by DenisKolodin** [comment]
I use R to generate data. For `density`, `distribution` and `inverse` I use `d<name>`, `p<name>` and `q<name>` methods. Mean, mode, and others I calculates with R manually.

But this case a little nasty: I've put testing data to wrong place and when I was implementing calculations I looked at the tests expectations and provide corresponding `pdf` or `cdf` calculations. I'll be more careful with it.

**Comment by IvanUkhov** [comment]
Sorry, I guess I misunderstood what the problem was. Now I see that you’ve just swapped the implementations of `distribution` and `density`. It wasn’t because of the test data you used. Your way of generating fixture data is perfectly legit. I also generate reference data using some software that can be trusted, and then I check these data agains my code.

**Comment by DenisKolodin** [comment]
Thank you!

**Pull request merged**
